<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php        
        echo $this->headTitle('CurrencyFair')
            ->setSeparator(' - ')
            ->setAutoEscape(false);
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')?>

        <!-- Scripts -->
        <?php
        
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
        ?>

    </head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                	data-target=".navbar-collapse">
                	<span class="icon-bar"></span> <span class="icon-bar"></span> <span
                		class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img
                	src="<?php echo $this->basePath('img/zf2-logo.png') ?>"
		alt="Zend Framework 2" />&nbsp;<?php echo $this->translate('CurrencyFair') ?></a>
            </div>
            
            <div class="collapse navbar-collapse">
            </div>
			<!--/.nav-collapse -->
		</div>

	</nav>

	<div class="container">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript()?>
    </body>
</html>
